<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PdfMerge.Application\PdfMerge.Application.csproj" />
    <ProjectReference Include="..\PdfMerge.Domain\PdfMerge.Domain.csproj" />
    <ProjectReference Include="..\PdfMerge.Infrastructure\PdfMerge.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Locales\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
